### ISSUE TITLE
trainging problem

### ISSUE THREAD

**Issue by tongpinmo** [yzcjtr/GeoNet#14]
1:I get the KITTI_odometry_grondtruth_poses data from tinghuiz/SfMLearner which only consists of 10 txt files,but there are 21 sequences in KITTI odometry dataset ,do i get the wrong groundtruth pose data?
2:in the process of training flow,when the iteration is 15200,the problem is :

Iteration: [  14700] | Time: 0.3787s/iter | Loss: 1.504
2018-07-01 17:51:40.590857: W tensorflow/core/framework/op_kernel.cc:1192] Invalid argument: Expected image (JPEG, PNG, or GIF), got empty file
	 [[Node: DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=0, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ReaderReadV2:1)]]
Iteration: [  14800] | Time: 0.3839s/iter | Loss: 1.462
Iteration: [  14900] | Time: 0.3801s/iter | Loss: 1.380
Iteration: [  15000] | Time: 0.3811s/iter | Loss: 1.538
Iteration: [  15100] | Time: 0.4323s/iter | Loss: 1.279
Iteration: [  15200] | Time: 0.3785s/iter | Loss: 1.250

2018-07-01 17:55:13.338006: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: RandomShuffleQueue '_2_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 4, current size 0)
	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_UINT8, DT_UINT8, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
2018-07-01 17:55:13.338261: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: RandomShuffleQueue '_2_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 4, current size 0)
	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_UINT8, DT_UINT8, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
2018-07-01 17:55:13.338448: W tensorflow/core/framework/op_kernel.cc:1192] Out of range: RandomShuffleQueue '_2_shuffle_batch/random_shuffle_queue' is closed and has insufficient elements (requested 4, current size 0)
	 [[Node: shuffle_batch = QueueDequeueManyV2[component_types=[DT_UINT8, DT_UINT8, DT_FLOAT], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/device:CPU:0"](shuffle_batch/random_shuffle_queue, shuffle_batch/n)]]
Traceback (most recent call last):
  File "geonet_main.py", line 166, in <module>
    tf.app.run()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "geonet_main.py", line 157, in main
    train()
  File "geonet_main.py", line 143, in train
    saver.save(sess, os.path.join(opt.checkpoint_dir, 'model'), global_step=step)
  File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 964, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/training/supervisor.py", line 792, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1231, in _single_operation_run
    target_list_as_strings, status, None)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Expected image (JPEG, PNG, or GIF), got empty file
	 [[Node: DecodeJpeg = DecodeJpeg[acceptable_fraction=1, channels=0, dct_method="", fancy_upscaling=true, ratio=1, try_recover_truncated=false, _device="/job:localhost/replica:0/task:0/device:CPU:0"](ReaderReadV2:1)]]

where prepare_training_flow:--dataset_dir=raw_data_KITTI/ --dataset_name=kitti_raw_stereo(if I set it as kitti_raw_eigen,there is nothing wrong)
and train_flow:--dataset_dir=resulting/formatted/data_flow/   -flownet_type=direct

i don't know why

**Comment by tongpinmo** [comment]
i change the num_threads and other parameter,but it doesn't work .the prepare_training_flow  is normal,i don't know why...can you help me?

**Comment by yzcjtr** [comment]
1. KITTI has only released the gt poses for seq. 00~10;
2. Seemingly you have missing images. You can check if all the images in the training list are normal.

**Comment by tongpinmo** [comment]
ok ,thank you very much ,i want to know what's the difference between kitti_raw_eigen and kitti_raw_stereo ,from the code ,their different test_scenes files make the training list different,and is there anything else that's important?can i only use the kitti_raw_eigen when prepare training?

**Comment by yzcjtr** [comment]
The splits are for conducting experiments on different tasks. Please refer to the experiment part of our paper for more details.

**Comment by tongpinmo** [comment]
i have solved it ,thank you
