### ISSUE TITLE
Unknown command line flag 'num_source'

### ISSUE THREAD

**Issue by live-lively** [yzcjtr/GeoNet#17]
when I run geonet_main.py in ubuntu 16.04LTS, it output as below, how shoule I do?
------------------------------------------------------------------------------------------------------------------
from ._conv import register_converters as _register_converters
Traceback (most recent call last):
  File "geonet_main.py", line 166, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "geonet_main.py", line 147, in main
    opt.num_source = opt.seq_length - 1
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/flags.py", line 88, in __setattr__
    return self.__dict__['__wrapped'].__setattr__(name, value)
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flagvalues.py", line 496, in __setattr__
    return self._set_unknown_flag(name, value)
  File "/usr/local/lib/python2.7/dist-packages/absl/flags/_flagvalues.py", line 374, in _set_unknown_flag
    raise _exceptions.UnrecognizedFlagError(name, value)
absl.flags._exceptions.UnrecognizedFlagError: Unknown command line flag 'num_source'

**Comment by yzcjtr** [comment]
I haven't encountered this. Which version of tensorflow are you using?

**Comment by danbo2** [comment]
I have the same error as well. Any solutions ?

**Comment by zacr0** [comment]
Hi @danbo2 , check the PR in my previous message, it contains a possible solution
